apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    deployed: ${TF_VAR_project}
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}

